CREATE TABLE [dbo].[japanese_characters] (
    [id]       INT           IDENTITY (1, 1) NOT NULL,
    [hiragana] NVARCHAR (3000) COLLATE Japanese_CI_AS_KS_WS NOT NULL,
    [katakana] NVARCHAR (3000) COLLATE Japanese_CI_AS_KS_WS NOT NULL,
    [romaji]   NVARCHAR (3000) COLLATE Japanese_CI_AS_KS_WS NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

INSERT INTO [dbo].[japanese_characters] ([hiragana], [katakana], [romaji])
VALUES
  (N'あ', N'ア', N'a'),
  (N'い', N'イ', N'i'),
  (N'う', N'ウ', N'u'),
  (N'え', N'エ', N'e'),
  (N'お', N'オ', N'o'),
  (N'か', N'カ', N'ka'),
  (N'き', N'キ', N'ki'),
  (N'く', N'ク', N'ku'),
  (N'け', N'ケ', N'ke'),
  (N'こ', N'コ', N'ko'),
  (N'さ', N'サ', N'sa'),
  (N'し', N'シ', N'shi'),
  (N'す', N'ス', N'su'),
  (N'せ', N'セ', N'se'),
  (N'そ', N'ソ', N'so'),
  (N'た', N'タ', N'ta'),
  (N'ち', N'チ', N'chi'),
  (N'つ', N'ツ', N'tsu'),
  (N'て', N'テ', N'te'),
  (N'と', N'ト', N'to'),
  (N'な', N'ナ', N'na'),
  (N'に', N'ニ', N'ni'),
  (N'ぬ', N'ヌ', N'nu'),
  (N'ね', N'ネ', N'ne'),
  (N'の', N'ノ', N'no'),
  (N'は', N'ハ', N'ha'),
  (N'ひ', N'ヒ', N'hi'),
  (N'ふ', N'フ', N'fu'),
  (N'へ', N'ヘ', N'he'),
  (N'ほ', N'ホ', N'ho'),
  (N'ま', N'マ', N'ma'),
  (N'み', N'ミ', N'mi'),
  (N'む', N'ム', N'mu'),
  (N'め', N'メ', N'me'),
  (N'も', N'モ', N'mo'),
  (N'や', N'ヤ', N'ya'),
  (N'ゆ', N'ユ', N'yu'),
  (N'よ', N'ヨ', N'yo'),
  (N'ら', N'ラ', N'ra'),
  (N'り', N'リ', N'ri'),
  (N'る', N'ル', N'ru'),
  (N'れ', N'レ', N're'),
  (N'ろ', N'ロ', N'ro'),
  (N'わ', N'ワ', N'wa'),
  (N'を', N'ヲ', N'wo'),
  (N'ん', N'ン', N'n');